name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests and collect coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Format
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v

      - name: Run coverage
        run: go test -coverprofile=coverage.txt ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: k1lgor/bmi
